name = "work-completion-sheet"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat"]

[vars]
NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY = "pk_live_Y2xlcmsuYm90b25kYjEud29ya2Vycy5kZXYk"
NEXT_PUBLIC_CLERK_SIGN_IN_URL = "/sign-in"
NEXT_PUBLIC_CLERK_SIGN_UP_URL = "/sign-up"
NEXT_PUBLIC_CLERK_AFTER_SIGN_IN_URL = "/dashboard"
NEXT_PUBLIC_CLERK_AFTER_SIGN_UP_URL = "/dashboard"

[observability]
enabled = true
